data_ingestion:
  train_data: "data/train.csv" 
  test_data: "data/test.csv"

data_transformation:
  All_feature_columns: ['season','weather','temp','atemp','humidity','windspeed',
                        'year','holiday','workingday','month','day','hour','week','weekday','peak',
                       'season2_Fall','season2_Spring','season2_Summer','season2_Winter',
                       'weather2_Clear','weather2_Heavy_Rain','weather2_Light_Snow','weather2_Mist']

  RFR_feature_columns: ['weather','temp','atemp','windspeed',
                       'workingday','season','holiday',
                       'hour','weekday','week','peak',
                       'season2_Fall','season2_Spring','season2_Summer','season2_Winter',
                      'weather2_Clear','weather2_Heavy_Rain','weather2_Light_Snow','weather2_Mist']

  GBR_feature_columns: ['weather','temp','atemp','humidity','windspeed',
                       'holiday','workingday','season',
                       'hour','weekday','year',
                      'season2_Fall','season2_Spring','season2_Summer','season2_Winter',
                       'weather2_Clear','weather2_Heavy_Rain','weather2_Light_Snow','weather2_Mist']

model_trainer:
  RFR_model1_path: "model/RFR1.pkl"
  RFR_model2_path: "model/RFR2.pkl"
  RFR_model3_path: "model/RFR3.pkl"

  GBR_model1_path: "model/GBR1.pkl"
  GBR_model2_path: "model/GBR2.pkl"
  GBR_model3_path: "model/GBR3.pkl"

model_predictor:
  submissions_csv_path: "submissions/submission.csc"
  submission2_csv_path: "submissions/submission2.csv"